on:
  schedule:
    - cron:  '0 0 * * *'
name: Scrape Data
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: python3 -m pip install -r requirements.txt
    - name: Scrape
      run: python3 fetch.py
    - uses: mikeal/publish-to-github-action@e5a27bbb5174edae8930d2250fc98a3a32478f81
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
        BRANCH_NAME: main
